layout: sidebar
style: dark



plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
   linkedin: ramitbedi
  # mastodon: your_username
  # medium: your_username
   stackoverflow: 12288655
  # telegram: your_username
   twitter: ramitbedi
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/java/java.png
  - name: Maven
    web_url: https://github.com/topics/maven
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/maven/maven.png  
  - name: Kubernetes
    web_url: https://github.com/topics/kubernetes
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/kubernetes/kubernetes.png
  - name: Go
    web_url: https://github.com/topics/go
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/go/go.png
  - name: Android
    web_url: https://github.com/topics/android 
  - name: AI
    web_url: https://github.com/topics/ai      
  - name: Deep learning
    web_url: https://github.com/topics/deep-learning
  - name: Code Review
    web_url: https://github.com/topics/code-review
  - name: Code Quality
    web_url: https://github.com/topics/code-quality     
  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png
  - name: Testing
    web_url: https://github.com/topics/testing
  - name: Selenium
    web_url: https://github.com/topics/selenium
  - name: Continuous Integration
    web_url: https://github.com/topics/continuous-integration
  - name: Cryptocurrency
    web_url: https://github.com/topics/cryptocurrency
  - name: Data-Visualization
    web_url: https://github.com/topics/data-visualization   
title: Aggregated Feeds
description: Personal RSS feed aggregator

gitusername: ramitbedi
gituseremail: ramitbedi@gmail.com
gituserbio: Software Engineer with thirst for knowledge and challenges.
gituserimage: https://avatars2.githubusercontent.com/u/11096909?s=88&u=73c72962da4a33fcdd2fd16363230743b475edd9&v=4
gituserdisplayname: Ramit Bedi
gituserlocation: San Jose

sources:
  Technology:
    DZONE:
      - http://feeds.dzone.com/home
      - http://feeds.dzone.com/publications
      - http://feeds.dzone.com/ai
      - http://feeds.dzone.com/devops
      - http://feeds.dzone.com/java
      - http://feeds.dzone.com/microservices
      - http://feeds.dzone.com/performance
    Geeks for Geeks:
      - https://www.geeksforgeeks.org/feed/  
    The Verge:
      - http://www.theverge.com/rss/index.xml 
    NY Times:
      - http://rss.nytimes.com/services/xml/rss/nyt/Technology.xml
    NPR:
      - https://www.npr.org/rss/rss.php?id=1019 
    The Atlantic:
      - https://www.theatlantic.com/feed/channel/technology/
  Finance:
    Investopedia:
      - https://www.investopedia.com/feedbuilder/feed/getfeed?feedName=rss_articles 
    eMoney Advisor:
      - http://blog.emoneyadvisor.com/feed/
    Wealthfront:
      - https://blog.wealthfront.com/feed
    Financial Advisor:
      - http://www.fa-mag.com/fa-news.feed?type=rss           
  Art:
    NY Times:
      - http://rss.nytimes.com/services/xml/rss/nyt/Arts.xml
    NPR:
      - https://www.npr.org/rss/rss.php?id=1008
    Pitchfork:
      - https://pitchfork.com/rss/all
    Rolling Stone:
      - https://www.rollingstone.com/movies/feed/
      - https://www.rollingstone.com/tv/feed/
      - https://www.rollingstone.com/music/feed
    r/ListenToThis:
      - https://www.reddit.com/r/ListenToThis.rss
    PetaPixel:
      - https://petapixel.com/feed/
  Business:
    NY Times:
      - http://rss.nytimes.com/services/xml/rss/nyt/Business.xml
    NPR:
      - https://www.npr.org/rss/rss.php?id=1006
    The Atlantic:
      - https://www.theatlantic.com/feed/channel/business/
    Motley Fool:
      - https://www.fool.com/a/feeds/foolwatch?format=rss2&id=foolwatch&apikey=foolwatch-feed
    Seeking Alpha:
      - https://seekingalpha.com/api/sa/combined/BA.xml
      - https://seekingalpha.com/api/sa/combined/AAPL.xml
      - https://seekingalpha.com/api/sa/combined/AMT.xml
  COVID-19:
    US CDC:
      - https://tools.cdc.gov/api/v2/resources/media/403372.rss
    WHO:
      - https://www.who.int/rss-feeds/news-english.xml
    NY Times:
      - https://rss.nytimes.com/services/xml/rss/nyt/Health.xml
    NPR:
      - https://www.npr.org/rss/rss.php?id=1031
    Mayo Clinic:
      - https://newsnetwork.mayoclinic.org/category/covid-19/feed/
  Headlines:
    NY Times:
      - http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
    NPR:
      - https://www.npr.org/rss/rss.php?id=1019
    PBS:
      - https://www.pbs.org/newshour/feeds/rss/headlines
    BBC:
      - http://feeds.bbci.co.uk/news/rss.xml
    TOI:
      - https://timesofindia.indiatimes.com/rssfeedstopstories.cms?x=1
    Al Jazeera:
      - https://www.aljazeera.com/xml/rss/all.xml
    Reuters:
      - http://feeds.reuters.com/reuters/topNews?format=xml
    AP:
      - http://twitrss.me/twitter_user_to_rss/?user=AP
  Bay Area:
    KRON 4:
      - https://www.kron4.com/news/feed/
    Mercury News:
      - https://www.mercurynews.com/feed/ 
    NBC Bay Area:
      - https://www.nbcbayarea.com/news/local/feed/ 
    Apple News:
      - https://www.apple.com/newsroom/rss-feed.rss   
  Politics:
    NY Times:
      - http://rss.nytimes.com/services/xml/rss/nyt/Politics.xml
    NPR:
      - https://www.npr.org/rss/rss.php?id=1014
    The Atlantic:
      - https://www.theatlantic.com/feed/channel/politics/
    Politifact:
      - https://www.politifact.com/feeds/statements/truth-o-meter/
    FactCheck.org:
      - https://www.factcheck.org/feed/
  Popular:
    NY Times:
      - http://rss.nytimes.com/services/xml/rss/nyt/Business.xml
    NPR:
      - https://www.npr.org/rss/rss.php?id=1048
    Rolling Stone:
      - https://www.rollingstone.com/culture/feed/
    The Atlantic:
      - https://www.theatlantic.com/feed/channel/entertainment/
  Science:
    NY Times:
      - http://rss.nytimes.com/services/xml/rss/nyt/Science.xml
    NPR:
      - https://www.npr.org/rss/rss.php?id=1007
    The Atlantic:
      - https://www.theatlantic.com/feed/channel/science/
  Personal:
    Hackaday:
      - https://hackaday.com/blog/feed/
    Boeing:
      - https://news.google.com/rss/search?q=boeing&sources=news&hl=en-US&gl=US&ceid=US:en
    Markdown:
      - https://news.google.com/rss/search?q=markdown+writing&sources=news&hl=en-US&gl=US&ceid=US:en
    OER:
      - https://news.google.com/rss/search?q=open+educational+resources&sources=news&hl=en-US&gl=US&ceid=US:en 
  Weather:
    NOAA:
      - https://w1.weather.gov/xml/current_obs/KSJC.rss
      - https://w1.weather.gov/xml/current_obs/KSFO.rss
      - https://w1.weather.gov/xml/current_obs/KHAF.rss
      - https://w1.weather.gov/xml/current_obs/KLAX.rss
      - https://w1.weather.gov/xml/current_obs/KBUR.rss
      - https://w1.weather.gov/xml/current_obs/KOAK.rss
  World:
    NY Times:
      - http://rss.nytimes.com/services/xml/rss/nyt/Science.xml
    NPR:
      - https://www.npr.org/rss/rss.php?id=1007
    The Atlantic:
      - https://www.theatlantic.com/feed/channel/international/

  
  